TOPLEVEL_LANG = verilog
TOPLEVEL = noc_system  # Your multi-core NoC RTL
MODULE = redteam_tests

VERILOG_SOURCES = $(shell pwd)/rtl/*.v

SIM = verilator
export COCOTB_REDUCED_LOG_FMT=1

include $(shell cocotb-config --makefiles)/Makefile.sim
