// Generated by AVA AGENT_B — plain-SV self-checking smoke test for cv32e40p_alu
// Runs on any Verilog simulator (iverilog/verilator); no UVM required.
`timescale 1ns/1ps
module cv32e40p_alu_smoke_tb;
  logic clk;
  logic rst_n;
  logic enable_i;
  logic operator_i;
  logic [31:0] operand_a_i;
  logic [31:0] operand_b_i;
  logic [31:0] operand_c_i;
  logic [1:0] vector_mode_i;
  logic [4:0] bmask_a_i;
  logic [4:0] bmask_b_i;
  logic [1:0] imm_vec_ext_i;
  logic is_clpx_i;
  logic is_subrot_i;
  logic [1:0] clpx_shift_i;
  logic [31:0] result_o;
  logic comparison_result_o;
  logic ready_o;
  logic ex_ready_i;

  cv32e40p_alu dut (
    .clk(clk),
    .rst_n(rst_n),
    .enable_i(enable_i),
    .operator_i(operator_i),
    .operand_a_i(operand_a_i),
    .operand_b_i(operand_b_i),
    .operand_c_i(operand_c_i),
    .vector_mode_i(vector_mode_i),
    .bmask_a_i(bmask_a_i),
    .bmask_b_i(bmask_b_i),
    .imm_vec_ext_i(imm_vec_ext_i),
    .is_clpx_i(is_clpx_i),
    .is_subrot_i(is_subrot_i),
    .clpx_shift_i(clpx_shift_i),
    .result_o(result_o),
    .comparison_result_o(comparison_result_o),
    .ready_o(ready_o),
    .ex_ready_i(ex_ready_i)
  );

  initial begin clk = 0; forever #5 clk = ~clk; end

  integer i;
  initial begin
    $dumpfile("cv32e40p_alu_smoke.vcd"); $dumpvars(0, cv32e40p_alu_smoke_tb);
    rst_n = 1'b0;
    repeat (5) @(posedge clk);
    rst_n = 1'b1;
    for (i = 0; i < 100; i = i + 1) begin
      @(posedge clk);
      enable_i <= $random;
      operator_i <= $random;
      operand_a_i <= $random;
      operand_b_i <= $random;
      operand_c_i <= $random;
      vector_mode_i <= $random;
      bmask_a_i <= $random;
      bmask_b_i <= $random;
      imm_vec_ext_i <= $random;
      is_clpx_i <= $random;
      is_subrot_i <= $random;
      clpx_shift_i <= $random;
      ex_ready_i <= $random;
    end
    @(posedge clk);
    // Basic liveness check: DUT did not X-out its outputs after reset.
    if (^result_o === 1'bx) $display("[cv32e40p_alu_smoke_tb] WARN: result_o is X");
    if (^comparison_result_o === 1'bx) $display("[cv32e40p_alu_smoke_tb] WARN: comparison_result_o is X");
    if (^ready_o === 1'bx) $display("[cv32e40p_alu_smoke_tb] WARN: ready_o is X");
    $display("[cv32e40p_alu_smoke_tb] PASS: %0d cycles driven", i);
    $finish;
  end

  // watchdog
  initial begin #100000; $display("[cv32e40p_alu_smoke_tb] TIMEOUT"); $finish; end
endmodule
