// Generated by AVA AGENT_B — UVM package for cv32e40p_alu
`ifndef CV32E40P_ALU_PKG_SV
`define CV32E40P_ALU_PKG_SV
package cv32e40p_alu_pkg;
  import uvm_pkg::*;
  `include "uvm_macros.svh"

  // ---- transaction item ----
  class cv32e40p_alu_item extends uvm_sequence_item;
  rand logic enable_i;
  rand logic operator_i;
  rand logic [31:0] operand_a_i;
  rand logic [31:0] operand_b_i;
  rand logic [31:0] operand_c_i;
  rand logic [1:0] vector_mode_i;
  rand logic [4:0] bmask_a_i;
  rand logic [4:0] bmask_b_i;
  rand logic [1:0] imm_vec_ext_i;
  rand logic is_clpx_i;
  rand logic is_subrot_i;
  rand logic [1:0] clpx_shift_i;
  logic [31:0] result_o;
  logic comparison_result_o;
  logic ready_o;
  rand logic ex_ready_i;

    `uvm_object_utils_begin(cv32e40p_alu_item)
      `uvm_field_int(enable_i, UVM_ALL_ON)
      `uvm_field_int(operator_i, UVM_ALL_ON)
      `uvm_field_int(operand_a_i, UVM_ALL_ON)
      `uvm_field_int(operand_b_i, UVM_ALL_ON)
      `uvm_field_int(operand_c_i, UVM_ALL_ON)
      `uvm_field_int(vector_mode_i, UVM_ALL_ON)
      `uvm_field_int(bmask_a_i, UVM_ALL_ON)
      `uvm_field_int(bmask_b_i, UVM_ALL_ON)
      `uvm_field_int(imm_vec_ext_i, UVM_ALL_ON)
      `uvm_field_int(is_clpx_i, UVM_ALL_ON)
      `uvm_field_int(is_subrot_i, UVM_ALL_ON)
      `uvm_field_int(clpx_shift_i, UVM_ALL_ON)
      `uvm_field_int(result_o, UVM_ALL_ON)
      `uvm_field_int(comparison_result_o, UVM_ALL_ON)
      `uvm_field_int(ready_o, UVM_ALL_ON)
      `uvm_field_int(ex_ready_i, UVM_ALL_ON)
    `uvm_object_utils_end
    function new(string name="cv32e40p_alu_item"); super.new(name); endfunction
  endclass

  // ---- driver ----
  class cv32e40p_alu_driver extends uvm_driver #(cv32e40p_alu_item);
    `uvm_component_utils(cv32e40p_alu_driver)
    virtual cv32e40p_alu_if vif;
    function new(string name, uvm_component parent); super.new(name,parent); endfunction
    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      if (!uvm_config_db#(virtual cv32e40p_alu_if)::get(this,"","vif",vif))
        `uvm_fatal("NOVIF","virtual interface not set for driver")
    endfunction
    task run_phase(uvm_phase phase);
      forever begin
        cv32e40p_alu_item tr;
        seq_item_port.get_next_item(tr);
        @(vif.drv_cb);
        vif.drv_cb.enable_i <= tr.enable_i;
        vif.drv_cb.operator_i <= tr.operator_i;
        vif.drv_cb.operand_a_i <= tr.operand_a_i;
        vif.drv_cb.operand_b_i <= tr.operand_b_i;
        vif.drv_cb.operand_c_i <= tr.operand_c_i;
        vif.drv_cb.vector_mode_i <= tr.vector_mode_i;
        vif.drv_cb.bmask_a_i <= tr.bmask_a_i;
        vif.drv_cb.bmask_b_i <= tr.bmask_b_i;
        vif.drv_cb.imm_vec_ext_i <= tr.imm_vec_ext_i;
        vif.drv_cb.is_clpx_i <= tr.is_clpx_i;
        vif.drv_cb.is_subrot_i <= tr.is_subrot_i;
        vif.drv_cb.clpx_shift_i <= tr.clpx_shift_i;
        vif.drv_cb.ex_ready_i <= tr.ex_ready_i;
        `uvm_info("DRV", $sformatf("drove %s", tr.sprint()), UVM_HIGH)
        seq_item_port.item_done();
      end
    endtask
  endclass

  // ---- monitor ----
  class cv32e40p_alu_monitor extends uvm_monitor;
    `uvm_component_utils(cv32e40p_alu_monitor)
    virtual cv32e40p_alu_if vif;
    uvm_analysis_port #(cv32e40p_alu_item) ap;
    function new(string name, uvm_component parent);
      super.new(name,parent); ap = new("ap", this);
    endfunction
    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      if (!uvm_config_db#(virtual cv32e40p_alu_if)::get(this,"","vif",vif))
        `uvm_fatal("NOVIF","virtual interface not set for monitor")
    endfunction
    task run_phase(uvm_phase phase);
      forever begin
        cv32e40p_alu_item tr = cv32e40p_alu_item::type_id::create("tr");
        @(vif.mon_cb);
        tr.result_o = vif.mon_cb.result_o;
        tr.comparison_result_o = vif.mon_cb.comparison_result_o;
        tr.ready_o = vif.mon_cb.ready_o;
        tr.enable_i = vif.drv_cb.enable_i;
        tr.operator_i = vif.drv_cb.operator_i;
        tr.operand_a_i = vif.drv_cb.operand_a_i;
        tr.operand_b_i = vif.drv_cb.operand_b_i;
        tr.operand_c_i = vif.drv_cb.operand_c_i;
        tr.vector_mode_i = vif.drv_cb.vector_mode_i;
        tr.bmask_a_i = vif.drv_cb.bmask_a_i;
        tr.bmask_b_i = vif.drv_cb.bmask_b_i;
        tr.imm_vec_ext_i = vif.drv_cb.imm_vec_ext_i;
        tr.is_clpx_i = vif.drv_cb.is_clpx_i;
        tr.is_subrot_i = vif.drv_cb.is_subrot_i;
        tr.clpx_shift_i = vif.drv_cb.clpx_shift_i;
        tr.ex_ready_i = vif.drv_cb.ex_ready_i;
        ap.write(tr);
      end
    endtask
  endclass

  // ---- sequencer ----
  typedef uvm_sequencer #(cv32e40p_alu_item) cv32e40p_alu_sequencer;

  // ---- agent ----
  class cv32e40p_alu_agent extends uvm_agent;
    `uvm_component_utils(cv32e40p_alu_agent)
    cv32e40p_alu_driver    drv;
    cv32e40p_alu_monitor   mon;
    cv32e40p_alu_sequencer seqr;
    function new(string name, uvm_component parent); super.new(name,parent); endfunction
    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      mon = cv32e40p_alu_monitor::type_id::create("mon", this);
      if (get_is_active() == UVM_ACTIVE) begin
        drv  = cv32e40p_alu_driver::type_id::create("drv", this);
        seqr = cv32e40p_alu_sequencer::type_id::create("seqr", this);
      end
    endfunction
    function void connect_phase(uvm_phase phase);
      if (get_is_active() == UVM_ACTIVE)
        drv.seq_item_port.connect(seqr.seq_item_export);
    endfunction
  endclass

  // ---- reference model (scaffolding: predict expected outputs) ----
  class cv32e40p_alu_refmodel extends uvm_component;
    `uvm_component_utils(cv32e40p_alu_refmodel)
    function new(string name, uvm_component parent); super.new(name,parent); endfunction
    // Predict the expected outputs for a stimulus item.
    virtual function cv32e40p_alu_item predict(cv32e40p_alu_item stim);
      cv32e40p_alu_item exp = cv32e40p_alu_item::type_id::create("exp");
      exp.copy(stim);
      // TODO: implement reference behaviour for 'cv32e40p_alu'.
      // AVA has a golden for this DUT class: pipeline_verifier.alu_eval / AGENT_H bitmanip/atomics goldens
      // The generator cannot infer DUT function; fill outputs below.
      // e.g. exp.result_o = <predicted from stim inputs>;
      return exp;
    endfunction
  endclass

  // ---- scoreboard ----
  `uvm_analysis_imp_decl(_mon)
  class cv32e40p_alu_scoreboard extends uvm_scoreboard;
    `uvm_component_utils(cv32e40p_alu_scoreboard)
    uvm_analysis_imp_mon #(cv32e40p_alu_item, cv32e40p_alu_scoreboard) mon_imp;
    cv32e40p_alu_refmodel ref_model;
    int matched, mismatched;
    function new(string name, uvm_component parent);
      super.new(name,parent); mon_imp = new("mon_imp", this);
    endfunction
    function void build_phase(uvm_phase phase);
      ref_model = cv32e40p_alu_refmodel::type_id::create("ref_model", this);
    endfunction
    function void write_mon(cv32e40p_alu_item observed);
      cv32e40p_alu_item expected = ref_model.predict(observed);
      if (expected.compare(observed)) matched++;
      else begin
        mismatched++;
        `uvm_error("SCB", $sformatf("mismatch\n exp: %s obs: %s",
                   expected.sprint(), observed.sprint()))
      end
    endfunction
    function void report_phase(uvm_phase phase);
      `uvm_info("SCB", $sformatf("matched=%0d mismatched=%0d", matched, mismatched), UVM_LOW)
    endfunction
  endclass

  // ---- functional coverage ----
  class cv32e40p_alu_coverage extends uvm_subscriber #(cv32e40p_alu_item);
    `uvm_component_utils(cv32e40p_alu_coverage)
    cv32e40p_alu_item item;
    covergroup cg;
      option.per_instance = 1;
    cp_enable_i: coverpoint item.enable_i {
      bins lo = {0}; bins hi = {1};
    }
    cp_operator_i: coverpoint item.operator_i {
      bins lo = {0}; bins hi = {1};
    }
    cp_operand_a_i: coverpoint item.operand_a_i {
      bins zero = {0};
      bins low  = {[1:15]};
      bins high = default;
    }
    cp_operand_b_i: coverpoint item.operand_b_i {
      bins zero = {0};
      bins low  = {[1:15]};
      bins high = default;
    }
    cp_operand_c_i: coverpoint item.operand_c_i {
      bins zero = {0};
      bins low  = {[1:15]};
      bins high = default;
    }
    cp_vector_mode_i: coverpoint item.vector_mode_i {
      bins zero = {0};
      bins low  = {[1:15]};
      bins high = default;
    }
    cp_bmask_a_i: coverpoint item.bmask_a_i {
      bins zero = {0};
      bins low  = {[1:15]};
      bins high = default;
    }
    cp_bmask_b_i: coverpoint item.bmask_b_i {
      bins zero = {0};
      bins low  = {[1:15]};
      bins high = default;
    }
    cp_imm_vec_ext_i: coverpoint item.imm_vec_ext_i {
      bins zero = {0};
      bins low  = {[1:15]};
      bins high = default;
    }
    cp_is_clpx_i: coverpoint item.is_clpx_i {
      bins lo = {0}; bins hi = {1};
    }
    cp_is_subrot_i: coverpoint item.is_subrot_i {
      bins lo = {0}; bins hi = {1};
    }
    cp_clpx_shift_i: coverpoint item.clpx_shift_i {
      bins zero = {0};
      bins low  = {[1:15]};
      bins high = default;
    }
    cp_result_o: coverpoint item.result_o {
      bins zero = {0};
      bins low  = {[1:15]};
      bins high = default;
    }
    cp_comparison_result_o: coverpoint item.comparison_result_o {
      bins lo = {0}; bins hi = {1};
    }
    cp_ready_o: coverpoint item.ready_o {
      bins lo = {0}; bins hi = {1};
    }
    cp_ex_ready_i: coverpoint item.ex_ready_i {
      bins lo = {0}; bins hi = {1};
    }
    endgroup
    function new(string name, uvm_component parent);
      super.new(name,parent); cg = new();
    endfunction
    function void write(cv32e40p_alu_item t); item = t; cg.sample(); endfunction
  endclass

  // ---- environment ----
  class cv32e40p_alu_env extends uvm_env;
    `uvm_component_utils(cv32e40p_alu_env)
    cv32e40p_alu_agent      agent;
    cv32e40p_alu_scoreboard scb;
    cv32e40p_alu_coverage   cov;
    function new(string name, uvm_component parent); super.new(name,parent); endfunction
    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      agent = cv32e40p_alu_agent::type_id::create("agent", this);
      scb   = cv32e40p_alu_scoreboard::type_id::create("scb", this);
      cov   = cv32e40p_alu_coverage::type_id::create("cov", this);
    endfunction
    function void connect_phase(uvm_phase phase);
      agent.mon.ap.connect(scb.mon_imp);
      agent.mon.ap.connect(cov.analysis_export);
    endfunction
  endclass

  // ---- sequences ----
  class cv32e40p_alu_random_seq extends uvm_sequence #(cv32e40p_alu_item);
    `uvm_object_utils(cv32e40p_alu_random_seq)
    rand int unsigned n_items = 100;
    function new(string name="cv32e40p_alu_random_seq"); super.new(name); endfunction
    task body();
      repeat (n_items) begin
        cv32e40p_alu_item tr = cv32e40p_alu_item::type_id::create("tr");
        start_item(tr);
        if (!tr.randomize()) `uvm_error("SEQ","randomize failed")
        finish_item(tr);
      end
    endtask
  endclass

  class cv32e40p_alu_smoke_seq extends uvm_sequence #(cv32e40p_alu_item);
    `uvm_object_utils(cv32e40p_alu_smoke_seq)
    function new(string name="cv32e40p_alu_smoke_seq"); super.new(name); endfunction
    task body();
      cv32e40p_alu_item tr = cv32e40p_alu_item::type_id::create("tr");
      start_item(tr);
      if (!tr.randomize()) `uvm_error("SEQ","randomize failed")
      finish_item(tr);
    endtask
  endclass

endpackage
`endif
