// Generated by AVA AGENT_B — UVM testbench top for cv32e40p_alu
`ifndef CV32E40P_ALU_TB_TOP_SV
`define CV32E40P_ALU_TB_TOP_SV
`include "uvm_macros.svh"

module cv32e40p_alu_tb_top;
  import uvm_pkg::*;
  import cv32e40p_alu_pkg::*;

  logic clk;
  logic rst_n;

  // clock
  initial begin clk = 1'b0; forever #5 clk = ~clk; end

  // interface
  cv32e40p_alu_if dut_if(.clk(clk));

  // DUT
  cv32e40p_alu dut (
    .clk(clk),
    .rst_n(dut_if.rst_n),
    .enable_i(dut_if.enable_i),
    .operator_i(dut_if.operator_i),
    .operand_a_i(dut_if.operand_a_i),
    .operand_b_i(dut_if.operand_b_i),
    .operand_c_i(dut_if.operand_c_i),
    .vector_mode_i(dut_if.vector_mode_i),
    .bmask_a_i(dut_if.bmask_a_i),
    .bmask_b_i(dut_if.bmask_b_i),
    .imm_vec_ext_i(dut_if.imm_vec_ext_i),
    .is_clpx_i(dut_if.is_clpx_i),
    .is_subrot_i(dut_if.is_subrot_i),
    .clpx_shift_i(dut_if.clpx_shift_i),
    .result_o(dut_if.result_o),
    .comparison_result_o(dut_if.comparison_result_o),
    .ready_o(dut_if.ready_o),
    .ex_ready_i(dut_if.ex_ready_i)
  );

  // reset
  initial begin
    rst_n = 1'b0;
    repeat (5) @(posedge clk);
    rst_n = 1'b1;
  end

  initial begin
    uvm_config_db#(virtual cv32e40p_alu_if)::set(null, "*", "vif", dut_if);
    run_test();
  end

  // global watchdog
  initial begin #100000; `uvm_fatal("TIMEOUT","watchdog expired"); end
endmodule
`endif
