// Generated by AVA AGENT_B — SVA assertion package for cv32e40p_alu
// Bind this to the DUT: bind cv32e40p_alu cv32e40p_alu_assertions u_asrt (.*);
`ifndef CV32E40P_ALU_ASSERTIONS_SV
`define CV32E40P_ALU_ASSERTIONS_SV
module cv32e40p_alu_assertions (
  input logic clk,
  input logic rst_n
  ,input logic [31:0] result_o,
  input logic comparison_result_o,
  input logic ready_o
);
  // result_o must be known one cycle after reset release
  property p_result_o_known;
    @(posedge clk) disable iff (rst_n == 1'b0)
    !$isunknown(result_o);
  endproperty
  a_result_o_known: assert property (p_result_o_known);

  // comparison_result_o must be known one cycle after reset release
  property p_comparison_result_o_known;
    @(posedge clk) disable iff (rst_n == 1'b0)
    !$isunknown(comparison_result_o);
  endproperty
  a_comparison_result_o_known: assert property (p_comparison_result_o_known);

  // ready_o must be known one cycle after reset release
  property p_ready_o_known;
    @(posedge clk) disable iff (rst_n == 1'b0)
    !$isunknown(ready_o);
  endproperty
  a_ready_o_known: assert property (p_ready_o_known);
endmodule
`endif
