// Generated by AVA AGENT_B — interface for cv32e40p_alu
`ifndef CV32E40P_ALU_IF_SV
`define CV32E40P_ALU_IF_SV

interface cv32e40p_alu_if (input logic clk);
  logic enable_i;
  logic operator_i;
  logic [31:0] operand_a_i;
  logic [31:0] operand_b_i;
  logic [31:0] operand_c_i;
  logic [1:0] vector_mode_i;
  logic [4:0] bmask_a_i;
  logic [4:0] bmask_b_i;
  logic [1:0] imm_vec_ext_i;
  logic is_clpx_i;
  logic is_subrot_i;
  logic [1:0] clpx_shift_i;
  logic [31:0] result_o;
  logic comparison_result_o;
  logic ready_o;
  logic ex_ready_i;

  // Driver clocking block: TB drives DUT inputs
  clocking drv_cb @(posedge clk);
    default input #1step output #1;
    output enable_i;
    output operator_i;
    output operand_a_i;
    output operand_b_i;
    output operand_c_i;
    output vector_mode_i;
    output bmask_a_i;
    output bmask_b_i;
    output imm_vec_ext_i;
    output is_clpx_i;
    output is_subrot_i;
    output clpx_shift_i;
    output ex_ready_i;
  endclocking

  // Monitor clocking block: TB samples DUT outputs
  clocking mon_cb @(posedge clk);
    default input #1step;
    input result_o;
    input comparison_result_o;
    input ready_o;
  endclocking

  modport drv (clocking drv_cb, input clk);
  modport mon (clocking mon_cb, input clk);
endinterface
`endif
