// Generated by AVA AGENT_B — UVM tests for cv32e40p_alu
`ifndef CV32E40P_ALU_TESTS_SV
`define CV32E40P_ALU_TESTS_SV
`include "uvm_macros.svh"
import uvm_pkg::*;
import cv32e40p_alu_pkg::*;

class cv32e40p_alu_base_test extends uvm_test;
  `uvm_component_utils(cv32e40p_alu_base_test)
  cv32e40p_alu_env env;
  function new(string name, uvm_component parent); super.new(name,parent); endfunction
  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    env = cv32e40p_alu_env::type_id::create("env", this);
  endfunction
endclass

class cv32e40p_alu_smoke_test extends cv32e40p_alu_base_test;
  `uvm_component_utils(cv32e40p_alu_smoke_test)
  function new(string name, uvm_component parent); super.new(name,parent); endfunction
  task run_phase(uvm_phase phase);
    cv32e40p_alu_smoke_seq seq = cv32e40p_alu_smoke_seq::type_id::create("seq");
    phase.raise_objection(this);
    seq.start(env.agent.seqr);
    #100;
    phase.drop_objection(this);
  endtask
endclass

class cv32e40p_alu_random_test extends cv32e40p_alu_base_test;
  `uvm_component_utils(cv32e40p_alu_random_test)
  function new(string name, uvm_component parent); super.new(name,parent); endfunction
  task run_phase(uvm_phase phase);
    cv32e40p_alu_random_seq seq = cv32e40p_alu_random_seq::type_id::create("seq");
    phase.raise_objection(this);
    if (!seq.randomize() with { n_items == 200; }) `uvm_error("TEST","rand failed")
    seq.start(env.agent.seqr);
    #200;
    phase.drop_objection(this);
  endtask
endclass
`endif
