"""Generated by AVA AGENT_B — cocotb testbench for cv32e40p_alu.
Run:  make SIM=verilator  (or icarus)   inside this directory.
"""
import random
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, RisingEdge


async def _reset(dut):
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 5)
    dut.rst_n.value = 1


@cocotb.test()
async def smoke(dut):
    """Clock + reset + a few random-stimulus cycles; check outputs resolve."""
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())
    await _reset(dut)
    await RisingEdge(dut.clk)
    assert dut.result_o.value.is_resolvable, f'result_o is X after reset'
    assert dut.comparison_result_o.value.is_resolvable, f'comparison_result_o is X after reset'
    assert dut.ready_o.value.is_resolvable, f'ready_o is X after reset'


@cocotb.test()
async def random_stimulus(dut):
    """Constrained-random drive over many cycles."""
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())
    await _reset(dut)
    for _ in range(200):
        await RisingEdge(dut.clk)
        dut.enable_i.value = random.getrandbits(1)
        dut.operator_i.value = random.getrandbits(1)
        dut.operand_a_i.value = random.getrandbits(32)
        dut.operand_b_i.value = random.getrandbits(32)
        dut.operand_c_i.value = random.getrandbits(32)
        dut.vector_mode_i.value = random.getrandbits(2)
        dut.bmask_a_i.value = random.getrandbits(5)
        dut.bmask_b_i.value = random.getrandbits(5)
        dut.imm_vec_ext_i.value = random.getrandbits(2)
        dut.is_clpx_i.value = random.getrandbits(1)
        dut.is_subrot_i.value = random.getrandbits(1)
        dut.clpx_shift_i.value = random.getrandbits(2)
        dut.ex_ready_i.value = random.getrandbits(1)
