#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
run_rtl_adapter.py — Agent E ↔ Agent B Bridge
===============================================
Bridges Agent E's ExternalDUTBackend contract to Agent B's run_rtl.py API.

Contract presented to Agent E (ExternalDUTBackend)
---------------------------------------------------
    python run_rtl_adapter.py \\
        --elf  <path/to/test.elf>   \\
        --sig  <path/to/dut.sig>    \\
        --isa  RV32IM               \\
        [--seed N] [--timeout N] [--sig-begin 0x...] [--sig-end 0x...]

Exit codes (matching Agent E's EXIT_* constants):
    0  signature file written and non-empty
    1  DUT simulation produced wrong answer (signature mismatch is Agent E's job)
    2  infrastructure failure (Agent B crash, timeout, missing outputs)
    3  Agent B binary / script not found

How it works
------------
1.  Probe for Agent B's run_rtl.py next to this file, or on PATH.
2.  Build a minimal manifest that Agent B's resolve_params() can read.
3.  Invoke Agent B in manifest mode:
        python run_rtl.py --manifest adapter_manifest.json \\
                          --sig-out dut.sig                \\
                          --sig-begin 0x... --sig-end 0x...
4.  Agent B writes outputs.signature = <path> into the manifest.
    We read that path, validate it, copy to --sig if necessary.
5.  On any failure, extract the best available error message and exit 2.

Signature address defaults
--------------------------
These must match the linker script generated by Agent E:
    LINK_ADDRESS   = 0x80000000     (text start)
    .signature     at ALIGN(8) after .bss

Agent E's linker script places begin_signature at roughly:
    0x80000000 + .text + .data + .tohost + .bss + alignment padding

Because the exact address varies per test we rely on Agent B's
--sig-begin / --sig-end parameters which Agent E can supply.  The
defaults here are conservative estimates for the 9 embedded tests.

If you have an exact begin_signature address (e.g. from `riscv32-unknown-elf-nm`),
pass --sig-begin / --sig-end explicitly.

Integration checklist for Agent B
----------------------------------
Agent B's run_rtl.py must:
  [✓] Accept --manifest PATH
  [✓] Read manifest.binary → ELF path
  [✓] Accept --sig-out PATH  (writes RISCOF words to that file)
  [✓] Accept --sig-begin / --sig-end hex addresses
  [✓] Write outputs.signature into the manifest on success
  [✓] Exit 0 on clean tohost, non-0 on crash
All of the above are confirmed present in the run_rtl.py uploaded to AVA.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import shutil
import subprocess
import sys
import tempfile
import time
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

log = logging.getLogger("agent_e.adapter")


# ─────────────────────────────────────────────────────────────────────────────
# Exit codes (mirror run_compliance.py EXIT_* constants)
# ─────────────────────────────────────────────────────────────────────────────

EXIT_PASS  = 0
EXIT_FAIL  = 1   # unused here; signature correctness is Agent E's responsibility
EXIT_CRASH = 2
EXIT_TOOL  = 3


# ─────────────────────────────────────────────────────────────────────────────
# Locating Agent B's run_rtl.py
# ─────────────────────────────────────────────────────────────────────────────

def _find_run_rtl() -> Optional[Path]:
    """
    Search for run_rtl.py in priority order:
      1. Same directory as this adapter.
      2. Parent directory (monorepo layout: agents/run_rtl_adapter.py + backends/run_rtl.py).
      3. AGENT_B_RTL env variable (explicit override).
      4. 'run_rtl.py' on sys.path / cwd.
    """
    here = Path(__file__).resolve().parent
    candidates: List[Path] = [
        here / "run_rtl.py",
        here.parent / "backends" / "run_rtl.py",
        here.parent / "run_rtl.py",
    ]
    env = os.environ.get("AGENT_B_RTL")
    if env:
        candidates.insert(0, Path(env).resolve())
    for p in candidates:
        if p.is_file():
            return p
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Atomic manifest write (same pattern as Agent B + Agent E)
# ─────────────────────────────────────────────────────────────────────────────

def _write_manifest(path: Path, data: Dict[str, Any]) -> None:
    """Write JSON atomically via tmp→rename."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=2))
    os.replace(tmp, path)


def _read_manifest(path: Path) -> Dict[str, Any]:
    with open(path) as f:
        return json.load(f)


# ─────────────────────────────────────────────────────────────────────────────
# Signature resolution helpers
# ─────────────────────────────────────────────────────────────────────────────

def _resolve_sig_path(
    manifest: Dict[str, Any],
    run_dir:  Path,
    sig_out:  Path,
) -> Optional[Path]:
    """
    Find the signature file produced by Agent B.

    Priority:
      1. manifest["outputs"]["signature"]  — set by Agent B when --sig-out given.
      2. run_dir / "signature.hex"         — Agent B's default output name.
      3. sig_out itself, if it already exists (Agent B wrote directly there).
    """
    sig_from_manifest = manifest.get("outputs", {}).get("signature")
    if sig_from_manifest:
        p = Path(sig_from_manifest)
        if p.is_file() and p.stat().st_size > 0:
            return p

    default = run_dir / "signature.hex"
    if default.is_file() and default.stat().st_size > 0:
        return default

    if sig_out.is_file() and sig_out.stat().st_size > 0:
        return sig_out

    return None


def _validate_sig_content(sig_path: Path) -> Tuple[bool, str]:
    """
    Basic validation: file must have ≥1 non-comment line of 8 hex chars.
    Returns (ok, error_message).
    """
    words = []
    for raw in sig_path.read_text(errors="replace").splitlines():
        raw = raw.strip()
        if not raw or raw.startswith("#"):
            continue
        clean = raw.lower()
        if clean.startswith("0x"):
            clean = clean[2:]
        if len(clean) != 8 or not all(c in "0123456789abcdef" for c in clean):
            continue   # skip malformed — Agent E's parser handles this
        words.append(clean)

    if not words:
        return False, f"Signature has no valid 32-bit words: {sig_path}"
    return True, ""


# ─────────────────────────────────────────────────────────────────────────────
# Core adapter logic
# ─────────────────────────────────────────────────────────────────────────────

def run_adapter(
    elf:       Path,
    sig_out:   Path,
    isa:       str,
    seed:      int,
    timeout:   int,
    sig_begin: str,
    sig_end:   str,
    verbose:   bool,
) -> int:
    """
    Main adapter flow.  Returns an EXIT_* code.
    """
    # ── Find Agent B ──────────────────────────────────────────────────────────
    run_rtl = _find_run_rtl()
    if run_rtl is None:
        log.error(
            "run_rtl.py not found.  Set AGENT_B_RTL env var or place "
            "run_rtl.py next to run_rtl_adapter.py."
        )
        return EXIT_TOOL

    log.info("Agent B: %s", run_rtl)

    # ── Build adapter work directory ──────────────────────────────────────────
    work_dir = sig_out.parent / f"_adapter_{uuid.uuid4().hex[:8]}"
    work_dir.mkdir(parents=True, exist_ok=True)

    # ── Write manifest for Agent B ────────────────────────────────────────────
    run_id      = str(uuid.uuid4())
    manifest_p  = work_dir / "adapter_manifest.json"
    _write_manifest(manifest_p, {
        "schemaversion": "2.0.0",
        "runid":         run_id,
        "seed":          seed,
        "binary":        str(elf.resolve()),
        "dut":           "rv32im_core",        # Agent B default; overridden by its own config
        "rundir":        str(work_dir),
        "isa":           isa.lower(),
        "rtl_files":     [],                   # Agent B reads these from its own config
        "phases":        {},
        "outputs":       {},
    })

    # ── Invoke Agent B ────────────────────────────────────────────────────────
    cmd = [
        sys.executable, str(run_rtl),
        "--manifest",  str(manifest_p),
        "--sig-out",   str(sig_out.resolve()),
        "--sig-begin", sig_begin,
        "--sig-end",   sig_end,
    ]
    if verbose:
        cmd.append("--verbose")

    log.info("[adapter] %s", " ".join(cmd))

    t0 = time.monotonic()
    try:
        proc = subprocess.run(
            cmd,
            capture_output = not verbose,
            text           = True,
            timeout        = timeout,
        )
    except subprocess.TimeoutExpired:
        log.error("Agent B timed out after %ds for %s", timeout, elf.name)
        _cleanup(work_dir)
        return EXIT_CRASH
    except FileNotFoundError:
        log.error("Python interpreter or run_rtl.py not found: %s", cmd[:3])
        _cleanup(work_dir)
        return EXIT_TOOL

    elapsed = time.monotonic() - t0
    log.info("Agent B finished in %.2fs  exit=%d", elapsed, proc.returncode)

    if verbose or proc.returncode not in (0, 1):
        if hasattr(proc, "stdout") and proc.stdout:
            sys.stdout.write(proc.stdout)
        if hasattr(proc, "stderr") and proc.stderr:
            sys.stderr.write(proc.stderr)

    # Agent B exits 1 for "simulation ran but tohost!=0" (test fail on DUT side)
    # and 0 for clean tohost.  We accept both and let Agent E decide.
    # Only non-0/1 exits indicate infrastructure crash.
    if proc.returncode not in (0, 1):
        log.error(
            "Agent B crashed (exit=%d).  stderr: %s",
            proc.returncode,
            (proc.stderr or "")[:300] if not verbose else "(printed above)",
        )
        _cleanup(work_dir)
        return EXIT_CRASH

    # ── Read back manifest to find signature path ─────────────────────────────
    try:
        updated_manifest = _read_manifest(manifest_p)
    except Exception as exc:
        log.error("Cannot read updated manifest: %s", exc)
        _cleanup(work_dir)
        return EXIT_CRASH

    sig_src = _resolve_sig_path(updated_manifest, work_dir, sig_out)

    if sig_src is None:
        log.error(
            "Agent B did not produce a signature file for %s.\n"
            "  Expected at: %s  or  manifest[outputs][signature]\n"
            "  Agent B may need --sig-out support (confirmed present in run_rtl.py).",
            elf.name, work_dir / "signature.hex",
        )
        _cleanup(work_dir)
        return EXIT_CRASH

    # ── Copy to Agent E's expected location ───────────────────────────────────
    if sig_src.resolve() != sig_out.resolve():
        shutil.copy2(sig_src, sig_out)
        log.debug("Copied sig %s → %s", sig_src, sig_out)

    # ── Validate ─────────────────────────────────────────────────────────────
    ok, err = _validate_sig_content(sig_out)
    if not ok:
        log.error("Signature validation failed: %s", err)
        _cleanup(work_dir)
        return EXIT_CRASH

    n_words = sum(
        1 for ln in sig_out.read_text().splitlines()
        if ln.strip() and not ln.strip().startswith("#")
    )
    log.info("Signature: %d word(s) written to %s", n_words, sig_out)

    _cleanup(work_dir)
    return EXIT_PASS


def _cleanup(work_dir: Path) -> None:
    """Remove adapter work directory (it is ephemeral)."""
    try:
        shutil.rmtree(work_dir, ignore_errors=True)
    except Exception:
        pass


# ─────────────────────────────────────────────────────────────────────────────
# Signature address helper
# ─────────────────────────────────────────────────────────────────────────────

def _nm_sig_addresses(elf: Path, objdump_bin: str = "") -> Tuple[Optional[str], Optional[str]]:
    """
    Use nm/objdump to find begin_signature and end_signature addresses.
    Returns (begin_hex, end_hex) with "0x" prefix, or (None, None) on failure.
    Used to override the --sig-begin / --sig-end defaults automatically.
    """
    # Try riscv*-nm first (lighter than objdump)
    nm_candidates = [
        "riscv32-unknown-elf-nm",
        "riscv64-unknown-elf-nm",
        "riscv-none-elf-nm",
    ]
    if objdump_bin:
        nm_candidates.insert(0, objdump_bin.replace("objdump", "nm"))

    nm = next((c for c in nm_candidates if shutil.which(c)), None)
    if nm is None:
        return None, None

    try:
        out = subprocess.check_output(
            [nm, str(elf)], text=True, timeout=10, stderr=subprocess.DEVNULL
        )
    except Exception:
        return None, None

    begin = end = None
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 3:
            continue
        addr = parts[0]
        sym  = parts[-1]
        if sym == "begin_signature":
            begin = f"0x{addr}"
        elif sym == "end_signature":
            end   = f"0x{addr}"

    return begin, end


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog        = "run_rtl_adapter.py",
        description = "Agent E ↔ Agent B bridge: presents Agent E's --sig contract "
                      "to ExternalDUTBackend, internally calls Agent B's run_rtl.py.",
        formatter_class = argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--elf",        required=True, type=Path,
                   help="ELF test binary to simulate")
    p.add_argument("--sig",        required=True, type=Path,
                   help="Output path for RISCOF signature file")
    p.add_argument("--isa",        default="RV32IM",
                   help="ISA string, e.g. RV32IM")
    p.add_argument("--seed",       type=int, default=0,
                   help="Random seed forwarded to Agent B")
    p.add_argument("--timeout",    type=int, default=120,
                   help="Total timeout for Agent B invocation (seconds)")
    p.add_argument("--sig-begin",  default="0x80002000",
                   help="Signature region start address (hex).  If 'auto', "
                        "resolved from ELF symbol table via nm.")
    p.add_argument("--sig-end",    default="0x80002040",
                   help="Signature region end address (hex).  If 'auto', "
                        "resolved from ELF symbol table via nm.")
    p.add_argument("--agent-b",    default=None, metavar="PATH",
                   help="Explicit path to Agent B's run_rtl.py.  "
                        "Overrides AGENT_B_RTL env var and auto-discovery.")
    p.add_argument("-v", "--verbose", action="store_true",
                   help="Forward Agent B's stdout/stderr to our output")
    return p


def main(argv: Optional[List[str]] = None) -> int:
    from typing import Optional as _Opt
    parser = _build_parser()
    args   = parser.parse_args(argv)

    level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level  = level,
        format = "%(asctime)s [%(levelname)-8s] %(name)s — %(message)s",
        stream = sys.stderr,
    )

    elf     = args.elf.resolve()
    sig_out = args.sig.resolve()

    # ── Pre-flight ────────────────────────────────────────────────────────────
    if not elf.exists():
        log.error("ELF not found: %s", elf)
        return EXIT_CRASH

    if elf.stat().st_size == 0:
        log.error("ELF is empty: %s", elf)
        return EXIT_CRASH

    magic = elf.read_bytes()[:4]
    if magic != b"\x7fELF":
        log.error("Not a valid ELF (magic=%s): %s", magic.hex(), elf)
        return EXIT_CRASH

    sig_out.parent.mkdir(parents=True, exist_ok=True)

    # ── Honour explicit --agent-b override ───────────────────────────────────
    if args.agent_b:
        os.environ["AGENT_B_RTL"] = args.agent_b

    # ── Auto-resolve signature addresses from ELF symbols ────────────────────
    sig_begin = args.sig_begin
    sig_end   = args.sig_end
    if sig_begin.lower() == "auto" or sig_end.lower() == "auto":
        b, e = _nm_sig_addresses(elf)
        if b and e:
            sig_begin = b
            sig_end   = e
            log.info("Signature addresses from nm: begin=%s  end=%s", b, e)
        else:
            log.warning(
                "Could not resolve signature addresses from ELF symbols; "
                "falling back to defaults (%s .. %s)",
                args.sig_begin, args.sig_end,
            )
            sig_begin = "0x80002000" if sig_begin.lower() == "auto" else sig_begin
            sig_end   = "0x80002040" if sig_end.lower() == "auto"   else sig_end

    log.info(
        "Adapter: elf=%s  sig=%s  isa=%s  seed=%d  begin=%s  end=%s",
        elf.name, sig_out.name, args.isa, args.seed, sig_begin, sig_end,
    )

    return run_adapter(
        elf       = elf,
        sig_out   = sig_out,
        isa       = args.isa,
        seed      = args.seed,
        timeout   = args.timeout,
        sig_begin = sig_begin,
        sig_end   = sig_end,
        verbose   = args.verbose,
    )


if __name__ == "__main__":
    sys.exit(main())
